FROM node:12

# Create app directory
WORKDIR /usr/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm ci --only=production

# Bundle app source
COPY . .
RUN chmod +x wait-for-it.sh

EXPOSE 8080
CMD [ "node", "./src/index.js" ]
